services:
  # Backend Web Service
  - type: web
    name: be-todo
    env: docker
    image:
      url: docker.io/yonten1234567890/todo-backend:02230313

  # Frontend Web Service
  - type: web
    name: fe-todo
    env: docker
    image:
      url: docker.io/yonten1234567890/todo-frontend:02230313

# Database (PostgreSQL)
databases:
  - name: todo-db
    databaseName: todo_db
    user: todo_user
